import { useEffect, useState } from "preact/hooks";
import { Modal } from "./Modal";
import { addNumber, addSprite } from "../../editorView";
import gameAtom from "../atoms/gameAtom";
import { useAtom } from "jotai";
import {
  WNumberDescription,
  WSoundDescriptionJSFXR,
} from "../../../share/types";
import { saveGame } from "../../storage";
import { onAddResourceListener } from "../Listeners";

export function ModalRessource() {
  const [isOpened, setIsOpened] = useState(false);
  const [isModalSoundOpened, setIsModalSoundOpened] = useState(false);

  useEffect(() => {
    onAddResourceListener.addListener(() => {
      setIsOpened(true);
    });
  }, []);

  const [game, setGame] = useAtom(gameAtom);

  const [labelSoundValue, setLabelSoundValue] = useState("");
  const [soundCodeValue, setSoundCodeValue] = useState("");

  function addImage() {
    let input = document.createElement("input");
    input.type = "file";
    input.accept = "image/svg+xml";

    input.addEventListener("change", () => {
      if (!input.files) return;

      addSprite(input.files![0]);
      setIsOpened(false);
    });

    input.click();
  }

  function addSound() {
    setIsOpened(false);
    setIsModalSoundOpened(true);
  }

  function handleAddSound() {
    let codeValue = (document.getElementById("soundCode") as HTMLInputElement)
      .value;
    let nameValue = (document.getElementById("soundName") as HTMLInputElement)
      .value;

    let sound: WSoundDescriptionJSFXR = {
      type: "jsfxr",
      content: codeValue,
      id: game.nextAvailableSoundId,
      name: nameValue,
    };

    game.sounds.push(sound);
    game.nextAvailableSoundId++;

    saveGame(game);
    setGame(game);

    setIsOpened(false);
  }

  function addText() {
    let wNumber: WNumberDescription = {
      id: game.nextAvailableNumberId,
      name: "Text" + game.nextAvailableNumberId,
      x: 0,
      y: 0,
      height: 30,
      numberDigit: 10,
    };

    saveGame({
      ...game,
      nextAvailableNumberId: game.nextAvailableNumberId + 1,
      numbers: game.numbers.concat(wNumber),
    });
    setGame({
      ...game,
      nextAvailableNumberId: game.nextAvailableNumberId + 1,
      numbers: game.numbers.concat(wNumber),
    });

    addNumber(wNumber);
    setIsOpened(false);
  }

  return (
    <>
      <Modal isOpened={isOpened} onClose={() => setIsOpened(false)}>
        <h2>Add Ressource</h2>

        <button className="button-primary" onClick={addImage}>
          🖼️ Add Sprite
        </button>
        <button className="button-primary" onClick={addSound}>
          🔊 Add Sound
        </button>
        <button className="button-primary" onClick={addText}>
          📝 Add Text
        </button>
      </Modal>

      <Modal
        isOpened={isModalSoundOpened}
        onClose={() => setIsModalSoundOpened(false)}
      >
        <h2>Add Sounds</h2>

        <p>
          Watchy use{" "}
          <a href="https://sfxr.me/" target="_blank">
            JSFXR
          </a>{" "}
          to generate souynd. You can past the code generated by JSFXR here:
        </p>

        <label>Sound Name</label>
        <input
          value={labelSoundValue}
          onChange={(e) =>
            setLabelSoundValue((e.target as HTMLInputElement).value)
          }
          style={{ width: "100%" }}
        />

        <label>Sound code</label>
        <input
          value={soundCodeValue}
          onChange={(e) =>
            setSoundCodeValue((e.target as HTMLInputElement).value)
          }
          style={{ width: "100%", marginBottom: "10px" }}
        />

        <button className="button-primary" onClick={handleAddSound}>
          Add Sound
        </button>
      </Modal>
    </>
  );
}
