# Simple workflow for deploying static content to GitHub Pages
name: Build the game for Tauri

on: 
  workflow_dispatch:

concurrency:
  group: "tauri"
  cancel-in-progress: false

env:
  ITCH_USERNAME: bigaston
  ITCH_GAME_ID: watchy

jobs:
  publishTauri:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-20.04, windows-latest]

    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-20.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
      - name: install frontend dependencies
        run: npm install # change this to npm or pnpm depending on which one you use
      - uses: tauri-apps/tauri-action@v0
        id: tauri
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tagName: app-v__VERSION__ # the action automatically replaces \_\_VERSION\_\_ with the app version
          releaseName: 'App v__VERSION__'
          releaseBody: 'See the assets to download this version and install.'
          releaseDraft: true
          prerelease: false
      - name: Find good artifact
        uses: actions/github-script@v6
        id: findArtifact
        with:
          result-encoding: string
          script: |
            console.log(${{steps.tauri.outputs.artifactPaths}})
            const artifactPaths = ${{steps.tauri.outputs.artifactPaths}}
            let artifacts = artifactPaths.replace("[", "").replace("]", "").split(",")

            switch(${{matrix.platform}}) {
              case "macos-latest":
                return artifacts[1]
                break;
              case "ubuntu-20.04":
                return artifacts[1]
                break;
              case "windows-latest":
                return ./src-tauri/target/release/watchy.exe
                break;
            }
      - uses: actions/upload-artifact@v2
        with:
          name: ${{matrix.platform}}-build
          path: ${{ steps.findArtifact.outputs.result }}
      - name: Publish Just Executable
        uses: actions/upload-release-asset@v1.0.1
        if: matrix.platform == 'windows-latest'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.tauri.outputs.releaseUploadUrl }}
          asset_path: ./src-tauri/target/release/watchy.exe
          asset_name: watchy_standalone.exe
          asset_content_type: application/x-msdownload
      - run: echo ${{ steps.tauri.outputs.artifactPaths }}